"""empty message

Revision ID: 32eb68392515
Revises: 1f4fa1a07f14
Create Date: 2021-10-01 18:53:09.611209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32eb68392515'
down_revision = '1f4fa1a07f14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cocktail', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'image',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'alcohol_content',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'first_step',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'second_step',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'first_ingredient',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'second_ingredient',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'third_ingredient',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'fourth_ingredient',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'fifth_ingredient',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'first_measurement',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'second_measurement',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'third_measurement',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'fourth_measurement',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'fifth_measurement',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'garnish',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'glassware',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cocktail', 'glassware',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'garnish',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'fifth_measurement',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'fourth_measurement',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'third_measurement',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'second_measurement',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'first_measurement',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'fifth_ingredient',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'fourth_ingredient',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'third_ingredient',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'second_ingredient',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'first_ingredient',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'second_step',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'first_step',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'alcohol_content',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'image',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
