"""empty message

Revision ID: 439cba3e4a48
Revises: b273a261d83e
Create Date: 2021-09-17 22:59:06.138358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439cba3e4a48'
down_revision = 'b273a261d83e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cocktail', sa.Column('garnishes', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('glassware', sa.String(length=120), nullable=False))
    op.drop_constraint('cocktail_ingredients_key', 'cocktail', type_='unique')
    op.drop_constraint('cocktail_instructions_key', 'cocktail', type_='unique')
    op.drop_constraint('cocktail_measurements_key', 'cocktail', type_='unique')
    op.drop_constraint('cocktail_name_key', 'cocktail', type_='unique')
    op.drop_constraint('user_first_name_key', 'user', type_='unique')
    op.drop_constraint('user_last_name_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_last_name_key', 'user', ['last_name'])
    op.create_unique_constraint('user_first_name_key', 'user', ['first_name'])
    op.create_unique_constraint('cocktail_name_key', 'cocktail', ['name'])
    op.create_unique_constraint('cocktail_measurements_key', 'cocktail', ['measurements'])
    op.create_unique_constraint('cocktail_instructions_key', 'cocktail', ['instructions'])
    op.create_unique_constraint('cocktail_ingredients_key', 'cocktail', ['ingredients'])
    op.drop_column('cocktail', 'glassware')
    op.drop_column('cocktail', 'garnishes')
    # ### end Alembic commands ###
