"""empty message

Revision ID: 853f93de12a7
Revises: 439cba3e4a48
Create Date: 2021-09-17 23:04:38.591448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853f93de12a7'
down_revision = '439cba3e4a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cocktail', sa.Column('first_step', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('second_step', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('third_step', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('fourth_step', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('fifth_step', sa.String(length=120), nullable=False))
    op.drop_column('cocktail', 'instructions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cocktail', sa.Column('instructions', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('cocktail', 'fifth_step')
    op.drop_column('cocktail', 'fourth_step')
    op.drop_column('cocktail', 'third_step')
    op.drop_column('cocktail', 'second_step')
    op.drop_column('cocktail', 'first_step')
    # ### end Alembic commands ###
