"""empty message

Revision ID: 97cd4dd6991f
Revises: b98c9fbd5c28
Create Date: 2021-09-30 15:24:11.341368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cd4dd6991f'
down_revision = 'b98c9fbd5c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cocktail', sa.Column('alcohol_content', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('first_ingredient', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('second_ingredient', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('third_ingredient', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('fourth_ingredient', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('fifth_ingredient', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('first_measurement', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('second_measurement', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('third_measurement', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('fourth_measurement', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('fifth_measurement', sa.String(length=120), nullable=False))
    op.add_column('cocktail', sa.Column('garnish', sa.String(length=120), nullable=False))
    op.drop_column('cocktail', 'garnishes')
    op.drop_column('cocktail', 'measurements')
    op.drop_column('cocktail', 'ingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cocktail', sa.Column('ingredients', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('cocktail', sa.Column('measurements', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('cocktail', sa.Column('garnishes', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('cocktail', 'garnish')
    op.drop_column('cocktail', 'fifth_measurement')
    op.drop_column('cocktail', 'fourth_measurement')
    op.drop_column('cocktail', 'third_measurement')
    op.drop_column('cocktail', 'second_measurement')
    op.drop_column('cocktail', 'first_measurement')
    op.drop_column('cocktail', 'fifth_ingredient')
    op.drop_column('cocktail', 'fourth_ingredient')
    op.drop_column('cocktail', 'third_ingredient')
    op.drop_column('cocktail', 'second_ingredient')
    op.drop_column('cocktail', 'first_ingredient')
    op.drop_column('cocktail', 'alcohol_content')
    # ### end Alembic commands ###
