"""empty message

Revision ID: b98c9fbd5c28
Revises: 853f93de12a7
Create Date: 2021-09-23 15:47:10.957961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b98c9fbd5c28'
down_revision = '853f93de12a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cocktail', 'third_step',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'fourth_step',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('cocktail', 'fifth_step',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.add_column('user', sa.Column('date', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'date')
    op.alter_column('cocktail', 'fifth_step',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'fourth_step',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('cocktail', 'third_step',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
